[package]
name = "af-telemetry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
af-config = { path = "../af-config", version = "0.2.0-beta.14" }
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
