//! 启动期分层配置加载与运行期动态 Option 契约。

mod dynamic_options;
mod error;
mod loader;
mod model;
mod secret;

pub use dynamic_options::{
    DynamicOptionError, DynamicOptionSignal, DynamicOptionSnapshot, DynamicOptionSource,
    DynamicOptionSubscription,
};
pub use error::{ConfigError, CorsOriginError};
pub use loader::{
    CONFIG_FILE_ENV, DEFAULT_CONFIG_FILE, DEFAULT_ENV_FILE, ENV_PREFIX, load, load_from,
};
pub use model::{
    AUTH_SESSION_SIGNING_KEY_BYTES, AccountVerificationSettings, AlipayVerificationSettings,
    AppConfig, AuthSettings, BillingSettings, CREDENTIAL_ENCRYPTION_KEY_BYTES,
    ChannelProbeSettings, ClickHouseAnalyticsSettings, ClickHouseExportSettings, ClientIpSource,
    CorsOrigin, CredentialEncryptionSettings, DEFAULT_ALIPAY_VERIFICATION_TIMEOUT_SECS,
    DEFAULT_AUTH_LOOKUP_TIMEOUT_SECS, DEFAULT_AUTH_SESSION_TTL_SECS,
    DEFAULT_BILLING_FLUSH_INTERVAL_SECS, DEFAULT_BILLING_FLUSH_TIMEOUT_SECS,
    DEFAULT_CHANNEL_PROBE_BATCH_SIZE, DEFAULT_CHANNEL_PROBE_ENABLED,
    DEFAULT_CHANNEL_PROBE_INTERVAL_SECS, DEFAULT_CHANNEL_PROBE_TIMEOUT_SECS,
    DEFAULT_CLICKHOUSE_ANALYTICS_RESPONSE_BYTES, DEFAULT_CLICKHOUSE_ANALYTICS_TIMEOUT_SECS,
    DEFAULT_CLICKHOUSE_EXPORT_BACKFILL_BATCH_SIZE, DEFAULT_CLICKHOUSE_EXPORT_BATCH_SIZE,
    DEFAULT_CLICKHOUSE_EXPORT_INTERVAL_SECS, DEFAULT_CLICKHOUSE_EXPORT_REQUEST_BYTES,
    DEFAULT_CLICKHOUSE_EXPORT_TIMEOUT_SECS, DEFAULT_OAUTH_MAX_PENDING_AUTHORIZATIONS,
    DEFAULT_OAUTH_REFRESH_BATCH_SIZE, DEFAULT_OAUTH_REFRESH_BEFORE_EXPIRY_SECS,
    DEFAULT_OAUTH_REFRESH_CONCURRENCY, DEFAULT_OAUTH_REFRESH_ENABLED,
    DEFAULT_OAUTH_REFRESH_INTERVAL_SECS, DEFAULT_OAUTH_SESSION_TTL_SECS,
    DEFAULT_PAYMENT_SIGNATURE_TOLERANCE_SECS, DEFAULT_SHUTDOWN_TIMEOUT_SECS,
    DEFAULT_SUBSCRIPTION_CYCLE_BATCH_SIZE, DEFAULT_SUBSCRIPTION_CYCLE_ENABLED,
    DEFAULT_SUBSCRIPTION_CYCLE_INTERVAL_SECS, DEFAULT_SUBSCRIPTION_CYCLE_MAX_BATCHES_PER_RUN,
    DEFAULT_TURNSTILE_TIMEOUT_SECS, DatabaseConfig, HttpClientSettings, LogLevel,
    MAX_ALIPAY_VERIFICATION_APP_ID_BYTES, MAX_ALIPAY_VERIFICATION_BIZ_CODE_BYTES,
    MAX_ALIPAY_VERIFICATION_GATEWAY_BYTES, MAX_ALIPAY_VERIFICATION_KEY_BYTES,
    MAX_ALIPAY_VERIFICATION_TIMEOUT_SECS, MAX_AUTH_LOOKUP_TIMEOUT_SECS, MAX_AUTH_SESSION_TTL_SECS,
    MAX_BILLING_FLUSH_INTERVAL_SECS, MAX_BILLING_FLUSH_TIMEOUT_SECS, MAX_CHANNEL_PROBE_BATCH_SIZE,
    MAX_CHANNEL_PROBE_INTERVAL_SECS, MAX_CHANNEL_PROBE_TIMEOUT_SECS,
    MAX_CLICKHOUSE_ANALYTICS_RESPONSE_BYTES, MAX_CLICKHOUSE_ANALYTICS_TIMEOUT_SECS,
    MAX_CLICKHOUSE_EXPORT_BACKFILL_BATCH_SIZE, MAX_CLICKHOUSE_EXPORT_BATCH_SIZE,
    MAX_CLICKHOUSE_EXPORT_INTERVAL_SECS, MAX_CLICKHOUSE_EXPORT_REQUEST_BYTES,
    MAX_CLICKHOUSE_EXPORT_TIMEOUT_SECS, MAX_CREDENTIAL_ENCRYPTION_KEY_ID_BYTES,
    MAX_DATABASE_HEALTH_CHECK_TIMEOUT_SECS, MAX_OAUTH_CLIENT_ID_BYTES,
    MAX_OAUTH_CLIENT_SECRET_BYTES, MAX_OAUTH_PENDING_AUTHORIZATIONS, MAX_OAUTH_REFRESH_BATCH_SIZE,
    MAX_OAUTH_REFRESH_BEFORE_EXPIRY_SECS, MAX_OAUTH_REFRESH_CONCURRENCY,
    MAX_OAUTH_REFRESH_INTERVAL_SECS, MAX_OAUTH_SESSION_TTL_SECS, MAX_OPENAI_UPSTREAM_API_KEY_BYTES,
    MAX_OPENAI_UPSTREAM_BASE_URL_BYTES, MAX_OPENAI_UPSTREAM_MODEL_BYTES,
    MAX_PAYMENT_SECRET_KEY_BYTES, MAX_PAYMENT_SIGNATURE_TOLERANCE_SECS,
    MAX_PAYMENT_WEBHOOK_SECRET_BYTES, MAX_SHUTDOWN_TIMEOUT_SECS, MAX_SUBSCRIPTION_CYCLE_BATCH_SIZE,
    MAX_SUBSCRIPTION_CYCLE_BATCHES_PER_RUN, MAX_SUBSCRIPTION_CYCLE_INTERVAL_SECS,
    MAX_TRUSTED_PROXY_CIDRS, MAX_TURNSTILE_SECRET_KEY_BYTES, MAX_TURNSTILE_SITE_KEY_BYTES,
    MAX_TURNSTILE_TIMEOUT_SECS, MIN_OAUTH_SESSION_TTL_SECS, OAuthConfidentialClientSettings,
    OAuthPublicClientSettings, OAuthSettings, OpenAiUpstreamConfig, PaymentSettings, RedisSettings,
    ServerConfig, SubscriptionSettings, TelemetrySettings, TurnstileSettings,
};
pub use secret::SecretString;
